<?php

declare(strict_types=1);

namespace Cmp\Interface\Rest\Controller;

use Cmp\Application\Shared\Configuration\ConfigurationVersion;
use Cmp\Application\Shared\Idempotency\IdempotencyKey;
use Cmp\Application\Shared\Idempotency\RegisteredOutcome;
use Cmp\Application\Shared\Response\EvaluationTime;
use Cmp\Application\Shared\Result;
use Cmp\Application\User\AmendEmergencyContact;
use Cmp\Application\User\AuthenticatedCaller;
use Cmp\Application\User\ContactSetView;
use Cmp\Application\User\EmergencyContactCommand;
use Cmp\Application\User\NominateEmergencyContact;
use Cmp\Application\User\ReadContactsCommand;
use Cmp\Application\User\ReadEmergencyContacts;
use Cmp\Application\User\RemoveEmergencyContact;
use Cmp\Interface\Rest\Envelope;
use Cmp\Interface\Rest\FailureResponse;
use Cmp\Interface\Rest\Middleware\RequireIdempotencyKey;
use Cmp\Interface\Rest\Middleware\RequireSession;
use Cmp\Interface\Rest\Schema\EmergencyContactSchema;
use Cmp\Interface\Rest\ServedVersions;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use LogicException;

/**
 * `/profile/emergency-contacts` — `UC-048`, the four operations.
 *
 * `BE-005` makes this an adapter: it reads what the middleware resolved, builds
 * a command, invokes exactly one application service (`API-002` ‡) and
 * serialises the result. Every rule about what a contact may be, what makes one
 * unusable and who may act on one is elsewhere.
 *
 * It does not decide what a representation discloses either. `API-050` ‡ puts
 * that outside the adapter and `BE-002` keeps a Domain type out of this layer, so
 * the services answer with {@see ContactView} and {@see ContactSetView} and this
 * calls `toArray()` on what it is handed. An earlier version named
 * `EmergencyContact` here and the layer graph refused it.
 *
 * ## The `POST` is not in CMP-DOC-10, and is here anyway
 *
 * §11.2 lists `GET`, `PUT /{id}` and `DELETE /{id}` and no creation operation,
 * while `FRD-FR-181` — *"allow a user to nominate one or more emergency
 * contacts"* — is Specified, Mandatory, R1. `DB-022` ‡ rules out reading the
 * `PUT` as create-at-a-caller-supplied-identifier, because an exposed entity's
 * external identifier is randomly generated by the platform.
 *
 * CMP-DOC-04 governs over CMP-DOC-10 (README §3), a missing row withdraws no
 * requirement, and `POST` on the collection is how every other creatable
 * resource on this surface is created — `POST /vehicles`, `POST /rides`,
 * `POST /bookings`. The conflict is **reported**, at `CC-044`, rather than
 * quietly resolved.
 *
 * ## Success is `200`, including for the nomination
 *
 * `API-072` ‡ fixes a status range per **failure** branch and CMP-DOC-10 states
 * no success convention at all. Every operation this surface serves returns
 * `200`, and a second success code introduced here without a stated convention
 * is one the next resource would have to guess at.
 *
 * ## Nothing here reaches a contact
 *
 * No response tells a caller that anybody has been or will be informed.
 * `FRD-FR-195` ‡ forbids presenting a control the platform cannot honour and
 * `UX-165` ‡ forbids stating or implying that help is on the way;
 * `EmergencyContactLanguageTest` asserts that the served representation says
 * nothing of the kind, so the prohibition is checked rather than remembered.
 */
final class EmergencyContactController
{
    public function __construct(
        private readonly ReadEmergencyContacts $read,
        private readonly NominateEmergencyContact $nominate,
        private readonly AmendEmergencyContact $amend,
        private readonly RemoveEmergencyContact $remove,
        private readonly EmergencyContactSchema $schema,
        private readonly EvaluationTime $evaluatedAt,
        private readonly ConfigurationVersion $configurationVersion,
    ) {}

    /**
     * `GET` — `FRD-FR-181`'s read half, and `UC-048` step 1.
     */
    public function index(Request $request): JsonResponse
    {
        // API-065 / API-007: a safe method carries no key, so the read does not
        // ask for one — RequireIdempotencyKey does not require it on a GET either.
        $caller = $this->caller($request);

        $result = $this->read->execute(
            ReadContactsCommand::from($caller),
            $caller->actor(),
        );

        if ($result->isFailure()) {
            return FailureResponse::from($result->failure(), $this->evaluatedAt->stamp());
        }

        $contacts = $result->value();

        if (! $contacts instanceof ContactSetView) {
            throw new LogicException('UC-048: the read returns the set.');
        }

        return $this->envelope(['contacts' => $contacts->toArray()], false);
    }

    /**
     * `POST` — `FRD-FR-181`. See the class note for why this operation exists.
     */
    public function store(Request $request): JsonResponse
    {
        [$caller, $key] = $this->carriage($request);

        $refusal = $this->schema->refusalFor($request, $caller->actor()->reference());

        if ($refusal !== null) {
            return FailureResponse::from($refusal, $this->evaluatedAt->stamp());
        }

        return $this->contactResponse($this->nominate->execute(
            EmergencyContactCommand::toNominate($caller, $key, $this->string($request, 'phone_number'), $this->string($request, 'label')),
            $caller->actor(),
        ));
    }

    /**
     * `PUT /{id}` — `FRD-FR-182`, `FRD-FR-183`.
     */
    public function update(Request $request, string $version, string $id): JsonResponse
    {
        [$caller, $key] = $this->carriage($request);

        $refusal = $this->schema->refusalFor($request, $caller->actor()->reference());

        if ($refusal !== null) {
            return FailureResponse::from($refusal, $this->evaluatedAt->stamp());
        }

        return $this->contactResponse($this->amend->execute(
            EmergencyContactCommand::toAmend($caller, $key, $id, $this->string($request, 'phone_number'), $this->string($request, 'label')),
            $caller->actor(),
        ));
    }

    /**
     * `DELETE /{id}` — `FRD-FR-182`.
     */
    public function destroy(Request $request, string $version, string $id): JsonResponse
    {
        [$caller, $key] = $this->carriage($request);

        $result = $this->remove->execute(
            EmergencyContactCommand::toRemove($caller, $key, $id),
            $caller->actor(),
        );

        if ($result->isFailure()) {
            return FailureResponse::from($result->failure(), $this->evaluatedAt->stamp());
        }

        $outcome = $this->outcomeOf($result);

        return $this->envelope($outcome->representation() ?? [], $outcome->replayed());
    }

    /**
     * The nomination and the amendment serialise identically — both answer with
     * the contact as the platform now holds it.
     */
    private function contactResponse(Result $result): JsonResponse
    {
        if ($result->isFailure()) {
            return FailureResponse::from($result->failure(), $this->evaluatedAt->stamp());
        }

        $outcome = $this->outcomeOf($result);

        return $this->envelope($outcome->representation() ?? [], $outcome->replayed());
    }

    /**
     * `API-062` ‡ is applied in `ApplicationService` for every state-changing
     * command, so a write here cannot answer with anything else.
     */
    private function outcomeOf(Result $result): RegisteredOutcome
    {
        $outcome = $result->value();

        if (! $outcome instanceof RegisteredOutcome) {
            throw new LogicException('API-062 ‡: a state-changing operation answers with a registered outcome.');
        }

        return $outcome;
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function envelope(array $data, bool $replayed): JsonResponse
    {
        return Envelope::of($data, Envelope::meta(
            ServedVersions::CURRENT,
            $this->evaluatedAt->stamp(),
            $this->configurationVersion->current(),
            $replayed,
        ));
    }

    private function caller(Request $request): AuthenticatedCaller
    {
        $caller = $request->attributes->get(RequireSession::CALLER);

        if (! $caller instanceof AuthenticatedCaller) {
            throw new LogicException('An emergency-contact operation runs behind RequireSession.');
        }

        return $caller;
    }

    /**
     * A body field as a string, or null where it is absent.
     *
     * Absent and null are the same thing to the caller, and both mean *"do not
     * set this"*. Anything that is not a string is left to
     * `ContactDetails` to refuse with a reason — `API-041` keeps
     * well-formedness out of the adapter's hands, and a cast here would be this
     * layer deciding that `["a"]` means the label `Array`.
     */
    private function string(Request $request, string $field): ?string
    {
        $value = $request->json($field);

        return is_string($value) ? $value : null;
    }

    /**
     * The caller and the key, from what the middleware resolved.
     *
     * @return array{0: AuthenticatedCaller, 1: IdempotencyKey}
     */
    private function carriage(Request $request): array
    {
        $key = $request->headers->get(RequireIdempotencyKey::HEADER);

        if (! is_string($key)) {
            throw new LogicException(
                'A state-changing emergency-contact operation runs behind RequireIdempotencyKey.'
            );
        }

        return [$this->caller($request), IdempotencyKey::fromString($key)];
    }
}
